server:
  port: 8081

  servlet:
#    context-path: /api
    encoding:
      charset: UTF-8
      force: true

spring:
  config:
    import: env.yml

  kakao:
    admin-key: ${KAKAO_ADMIN_KEY}

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            scope:
              - account_email
            client-name: Kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            redirect-uri: ${KAKAO_REDIRECT_URL}
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    hikari:
      maximum-pool-size: 131      # 안전하게 설정
      minimum-idle: 10
      idle-timeout: 600000        # 10분
      max-lifetime: 1800000       # 30분

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl # 자동 camelCase-> underscore 전환 방지.
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
#        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect

jwt:
  header: Authorization
  secret: ${JWT_SECRET_KEY}
  access-token-expire: ${ACCESS_TOKEN_EXPIRE}
  refresh-token-expire: ${REFRESH_TOKEN_EXPIRE}

